# Generated by Django 2.2 on 2022-05-30 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_image_1', models.ImageField(upload_to='images')),
                ('shop_image_2', models.ImageField(upload_to='images')),
                ('shop_image_3', models.ImageField(upload_to='images')),
                ('shop_image_4', models.ImageField(upload_to='images')),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_location', models.CharField(max_length=500)),
                ('shop_phone', models.CharField(max_length=15)),
                ('shop_phone2', models.CharField(max_length=15)),
                ('shop_details', models.CharField(max_length=100)),
                ('shop_description', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Shop_profile',
            },
        ),
    ]
