# Generated by Django 2.2 on 2022-05-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0002_auto_20220527_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessservices',
            options={'verbose_name': 'Business Service', 'verbose_name_plural': 'Business Services'},
        ),
        migrations.AddField(
            model_name='businessservices',
            name='facebook',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessservices',
            name='fax',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessservices',
            name='googlemap',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessservices',
            name='instagram',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessservices',
            name='landphone',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessservices',
            name='linkedin',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessservices',
            name='twitter',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessservices',
            name='watsapp',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessservices',
            name='website',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='businessservices',
            table='business_services',
        ),
    ]
