# Generated by Django 4.0.2 on 2022-04-11 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0002_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('subcategories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorylocation', to='category_app.subcategory')),
            ],
        ),
    ]
