# Generated by Django 2.2 on 2022-06-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0003_remove_businessservices_landline_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessservices',
            name='landline_no',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
