# Generated by Django 2.2 on 2022-06-03 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0004_businessservices_landline_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessservices',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.SubCategory'),
        ),
    ]
