# Generated by Django 4.0.2 on 2022-05-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0004_alter_locations_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
