# Generated by Django 4.0.2 on 2022-05-11 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0005_sublocations'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=62)),
                ('description', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('branch_location', models.CharField(max_length=64)),
                ('phone_no', models.CharField(max_length=16)),
                ('landline_no', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Service',
                'verbose_name_plural': 'Business Services',
                'db_table': 'business_services',
            },
        ),
        migrations.DeleteModel(
            name='SubLocations',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='locations',
            table='locations',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='sub_category',
        ),
        migrations.AddField(
            model_name='businessservices',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.locations'),
        ),
        migrations.AddField(
            model_name='businessservices',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.subcategory'),
        ),
    ]
