# Generated by Django 2.2 on 2022-06-03 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0005_auto_20220603_0833'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessServices',
        ),
    ]
