# Generated by Django 4.0.2 on 2022-05-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0006_businessservices_delete_sublocations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessservices',
            name='sub_category',
        ),
    ]
