# Generated by Django 2.2 on 2022-06-03 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0006_delete_businessservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=62)),
                ('description', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone_no', models.CharField(max_length=16)),
                ('landline_no', models.CharField(max_length=16)),
                ('website', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=16)),
                ('instagram', models.CharField(max_length=16)),
                ('twitter', models.CharField(max_length=16)),
                ('linkedin', models.CharField(max_length=16)),
                ('watsapp', models.CharField(max_length=16)),
                ('landphone', models.CharField(max_length=16)),
                ('fax', models.CharField(max_length=16)),
                ('googlemap', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.Category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.SubCategory')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.Locations')),
            ],
        ),
    ]
