# Generated by Django 4.0.2 on 2022-05-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0007_remove_businessservices_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessservices',
            name='branch_location',
        ),
    ]
