# Generated by Django 2.2 on 2022-06-27 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0008_privacypolicy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessservices',
            name='landphone',
        ),
    ]
