# Generated by Django 2.2 on 2022-07-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0010_auto_20220627_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessservices',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
